Bug 1967806 [wpt PR 52703] - Object.__init__ takes 0 arguments,
Automatic update from web-platform-tests
Object.__init__ takes 0 arguments (#52703)

When roll wpt tooling to chromium, we met the following error:
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Seems kwargs is not empty when running WPT with headless shell.

This is a follow up change on top of PR 52455
--

wpt-commits: a8cd1e7453ea08be3dad3adc05783e06c3e94dde
wpt-pr: 52703

Differential Revision: https://phabricator.services.mozilla.com/D250978

UltraBlame original commit: 21be78dd1b49447ac198b6d81d370108635e225a