Bug 1997476 - [ci] Fix extra_args block for autoland cron tasks, r=releng-reviewers,Eijebong
Autoland cron tasks currently match both non-default arms of this
$switch statement, which is causing errors like:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/build_decision/util/cli.py", line 60, in main
    args.command(vars(args))
  File "/usr/local/lib/python3.11/site-packages/build_decision/cli.py", line 39, in wrapper
    func(args)
  File "/usr/local/lib/python3.11/site-packages/build_decision/cli.py", line 75, in cron
    run(
  File "/usr/local/lib/python3.11/site-packages/build_decision/cron/__init__.py", line 127, in run
    _format_and_raise_error_if_any(failed_jobs)
  File "/usr/local/lib/python3.11/site-packages/build_decision/cron/__init__.py", line 136, in _format_and_raise_error_if_any
    raise RuntimeError(
RuntimeError: Cron jobs ['android-l10n-import'] couldn't be triggered properly. Reason(s):
```

Differential Revision: https://phabricator.services.mozilla.com/D270775

UltraBlame original commit: c617f248d8504636c91db3edecdfa20bd308806a