Bug 1749473 - fix autodoc import warning r=sylvestre DONTBUILD
NameError: name 'self' is not defined

Depends on D196011

Differential Revision: https://phabricator.services.mozilla.com/D196012

UltraBlame original commit: 3fd669fec7a06a0514e9f7c5d95cccdc69035809