Bug 1930887 [wpt PR 49133] - DOMException: Add test for Error.isError, a=testonly
Automatic update from web-platform-tests
DOMException: Add test for Error.isError

--

wpt-commits: d0a4c30040cbd8ad748bb0a53a5ac5c538277d40
wpt-pr: 49133

UltraBlame original commit: 1730171c5275386a766f47491bc1668512a3ca95