Bug 2038003 - Add missing ResultVariant.h include in dom/media/MediaData.h r=karlt
dom/media/MediaData.h references Result<already_AddRefed<VideoData>, MediaResult> which itself requires ResultVariant.h as
already_AddRefed<VideoData> and MediaResult require the packable variant strategy, per:

    error: implicit instantiation of undefined template
    'mozilla::detail::ResultImplementation<already_AddRefed<mozilla::VideoData>, mozilla::MediaResult, mozilla::detail::PackingStrategy::Variant>'

While the include could done at each instantiation site, doing it in
dom/media/MediaData.h saves CreateAndCopyData() callers from needing to
explicitly identify and include ResultVariant.h.

Differential Revision: https://phabricator.services.mozilla.com/D299243

UltraBlame original commit: a28bcc92edfd5f813cc4c45150980bf2e098c004