Bug 2052829 - Validate values in remaining CSSMathValue constructors; r=emilio,firefox-style-system-reviewers
Use the already implemented "adding the types" algorithm to validate values
passed to the CSSMathMin, CSSMathMax, and CSSMathClamp constructors.

This completes the missing constructor validation step for these subclasses and
allows incompatible types to throw a TypeError as required by the spec.

Differential Revision: https://phabricator.services.mozilla.com/D310755

UltraBlame original commit: 96e26e1e4076a2b8fe1c9269c89339ae3f0819be