Bug 1915550 - Fix document errors in urlbar dynamic-result-types. r=urlbar-reviewers,jteow
The error was:
ERROR: Unknown target name: "appendix b: using the webextensions api directly".

This is out of date documentation as we no longer support webextensions for dynamic result types.

Differential Revision: https://phabricator.services.mozilla.com/D220532

UltraBlame original commit: 19f452367a1d704a9d580dac8e4895dfd480b00d