Bug 1933625 - Fix verifyRunBlockingAndStrictModeSuppresionCount perf test r=petru
The UI test started to fail after [[ https://hg.mozilla.org/mozilla-central/rev/e9282534f59d | this ]] change landed.

The test was failing because:

```
java.lang.AssertionError: StrictMode suppression count does not match expected count.
expected:<17> but was:<18>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.mozilla.fenix.perf.StartupExcessiveResourceUseTest.verifyRunBlockingAndStrictModeSuppresionCount(StartupExcessiveResourceUseTest.kt:117)

```
Based on the error and changes Arturo made after the initial change was backed out due to failures, I've incremented the EXPECTED_SUPPRESSION_COUNT variable.

The UI test successfully passed 10x on Firebase ✅
All UI tests successfully passed 1x on Firebase ✅

Differential Revision: https://phabricator.services.mozilla.com/D230373

UltraBlame original commit: b2d530100640a3f5663ee4b7ea773925a2bed87d