Bug 2051730 - Avoid gcc -Wnonnull error in MozPromise MaybeChain.  r=xpcom-reviewers,nika
gcc sees that MozPromise InvokeCallbackMethod will return a null result
when SupportChaining is false and that MaybeChain doesn't null check
aFrom. But gcc doesn't know that aFrom should never be null when aTo is
non-null, so check and enforce it.

include/mozilla/MozPromise.h:692:21: error: 'this' pointer is null [-Werror=nonnull]
692 |       aFrom->ChainTo(aTo.forget(), "<chained completion promise>");

Differential Revision: https://phabricator.services.mozilla.com/D317380

UltraBlame original commit: 3efc7489949800209887723fab7afb4deb0459fb