Bug 1966538 [wpt PR 52556] - QuotaExceededError: Update to a DOMException derived interface,
Automatic update from web-platform-tests
QuotaExceededError: Update to a DOMException derived interface (#52556)

This change introduces a new QuotaExceededError class to
update the existing QuotaExceededError so services can return
`quota` and `requested` properties as needed. Implemented behind
RuntimeEnabledFlag `QuotaExceededErrorUpdate`. Changes to
update services throwing QuotaExceededError to use the new class
will be made in following changes (except for IDB which triggered
failures with this change).

Proposal: https://github.com/whatwg/webidl/pull/1465
Chromestatus: https://chromestatus.com/feature/6194847180128256
Bug: 406162261
Change-Id: I68e91e15724e64c0995365ee63d4abe627fe06d3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6516473
Reviewed-by: Domenic Denicola <domenicchromium.org>
Commit-Queue: Ayu Ishii <ayuichromium.org>
Reviewed-by: Joey Arhar <jarharchromium.org>
Reviewed-by: Joe Mason <joenotcharlesgoogle.com>
Cr-Commit-Position: refs/heads/main{#1460403}

Co-authored-by: Ayu Ishii <ayuichromium.org>
--

wpt-commits: 16a71c4282b0379f639051c0a3f98f3fcdaa2149
wpt-pr: 52556

Differential Revision: https://phabricator.services.mozilla.com/D250632

UltraBlame original commit: 869cbd71034aec8dfdce6d5342adbfc5d8dbf8e6