Bug 2038918 - Work around bindgen's mishandling of std::vector::_Scary_val. r=emilio,profiler-reviewers,canaltinova
The type is not actually useful since std::vector is already opaque, but
the way it's mishandled with libclang >= 21 leads to the following build
error:

error[E0425]: cannot find type `_Val_types` in this scope
   --> .../x86_64-pc-windows-msvc/debug/build/gecko-profiler-619884d94fdc4c30/out/gecko/bindings.rs:254:61
    |
254 |         pub type vector__Scary_val = root::std::_Vector_val<_Val_types>;
    |                                                             ^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
254 |         pub type vector__Scary_val<_Val_types> = root::std::_Vector_val<_Val_types>;
    |                                   ++++++++++++
For more information about this error, try `rustc --explain E0425`.
error: could not compile `gecko-profiler` (lib) due to 1 previous error

Differential Revision: https://phabricator.services.mozilla.com/D299983

UltraBlame original commit: cd26e0d6a49ebe3a25cf3281cde8f7ae80daab5a