Bug 1646256 - Make rust-analyzer and YouCompleteMe work with mozilla-central. r=sylvestre
The default configuration recommended here[1], while being a good
generic default, it doesn't quite work for mozilla-central as that peeks
the closest ancestor directory with a `Cargo.toml`.

For example, when editing under `servo/components/style`, it'd try to
use that directory as a project root and fail like:

```
    0: Failed to run `cargo metadata --manifest-path /home/emilio/src/moz/gecko/servo/components/style/Cargo.toml`
    1: Error during execution of `cargo metadata`:     Updating crates.io index
       error: failed to get `servo_atoms` as a dependency of package `style v0.0.1 (/home/emilio/src/moz/gecko/servo/components/style)`
       Caused by:
         failed to load source for dependency `servo_atoms`
```

Instead, we want to override it using the `'project_directory'` setting
so that we hit this path[2] and it works out of the box.

[1]: https://rust-analyzer.github.io/manual.html#youcompleteme
[2]: https://github.com/ycm-core/ycmd/blob/63db7ea37910a48addefe028fb5435c602acdec1/ycmd/completers/language_server/language_server_completer.py#L1914-L1916

Differential Revision: https://phabricator.services.mozilla.com/D79938

UltraBlame original commit: a1c1439da7332bf80df0eeca03d5ecf625ebc53b