Bug 2040285 - Add missing include files for do_CreateInstance. r=nkulatova DONTBUILD
The Thunerbird specific block needs this, otherwise I get
 `toolkit/xre/nsXREDirProvider.cpp:675:11: error: use of undeclared identifier 'do_CreateInstance' `

Differential Revision: https://phabricator.services.mozilla.com/D301010

UltraBlame original commit: 5ce97b6872f2298a70f381ea6d53d881f77a94e8