Bug 1954565 [wpt PR 51397] - [wptrunner] Fix missing `WebDriverCrashtestExecutor.is_alive()` method, a=testonly
Automatic update from web-platform-tests
[wptrunner] Fix missing `WebDriverCrashtestExecutor.is_alive()` method

The `TestDriverExecutorMixin` introduced for #13183 requires an
`is_alive()` executor method, but we forgot to add one for
`WebDriverCrashtestExecutor` [0]:

```
2025-03-17 05:05:54.246 INFO Starting runner
  ▶ ERROR [expected PASS] external/wpt/html/semantics/forms/the-select-element/customizable-select/nested-select-crash.html
  └   → Traceback (most recent call last):
  File "/Volumes/Work/s/w/ith4ri8l3q/external/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 831, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Work/s/w/ith4ri8l3q/external/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1239, in do_crashtest
    self.run_testdriver(protocol, url, timeout)
  File "/Volumes/Work/s/w/ith4ri8l3q/external/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 938, in run_testdriver
    is_alive = self.is_alive()
               ^^^^^^^^^^^^^
AttributeError: 'WebDriverCrashtestExecutor' object has no attribute 'is_alive'
```

Fixed by just inlining `protocol.is_alive()`, which is the same for all
executor types.

[0]: https://chromium-swarm.appspot.com/task?id=6fbcb3db3c2e6410

--

wpt-commits: 40ca1d44f30af4807a988b6598c04646de5340c1
wpt-pr: 51397

UltraBlame original commit: 1904bea271222c7462c60a63d6e90777061c63f2