Bug 1910834 - don't reload `taskgraph.main` in `mach taskgraph --diff`. r=releng-reviewers,taskgraph-reviewers,hneiva
Bug 1910179 caused `gecko_taskgraph.main` to use logic from `taskgraph.main`,
including the `format_taskgraph` function, that gets passed to subprocesses
when generating task graphs in parallel.
Reloading the `taskgraph.main` module means the original `format_taskgraph`
function is no longer pickleable:

"""
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 264, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function format_taskgraph at 0x7f47ab1cbce0>: it's not the same object as taskgraph.main.format_taskgraph
"""

Differential Revision: https://phabricator.services.mozilla.com/D219416

UltraBlame original commit: 3b476832986ab11f237f280a86c5fcdc7d6f474f