Bug 1657446 - Fix lint error after bug 1656044. r=nalexander
mozbuild.configure.ConfigureError: `help` should contain "{Enable|Disable}" because of non-constant default

Differential Revision: https://phabricator.services.mozilla.com/D86123

UltraBlame original commit: e17946640ffc985c2e428fcb1607cdd4bc725d5f