Bug 2066010 - media: Move MediaStreamSource::CloneResult destructor out-of-line. r=media-playback-reviewers,padenot,sergesanspaille,pehrsons
CloneResult's destructor needs the complete class definition for
MediaTrack when it calls the RefPtr destructor on mInputTrack. We don't
have the complete class definition in MediaStreamTrack.h because
MediaTrack is simply forward-declared.

In file included from dom/media/bridge/MediaModule.cpp:5:
In file included from obj-macos/xpcom/components/Components.h:10:
In file included from xpcom/base/nsCOMPtr.h:26:
mfbt/RefPtr.h:49:38: error: member access into incomplete type 'mozilla::MediaTrack'
   49 |   static void Release(U* aPtr) { aPtr->Release(); }
      |                                      ^
mfbt/RefPtr.h:409:62: note: in instantiation of member function 'mozilla::RefPtrTraits<mozilla::MediaTrack>::Release' requested here
  409 |     static void Release(U* aPtr) { mozilla::RefPtrTraits<U>::Release(aPtr); }
      |                                                              ^
mfbt/RefPtr.h:80:37: note: in instantiation of member function 'RefPtr<mozilla::MediaTrack>::ConstRemovingRefPtrTraits<mozilla::MediaTrack>::Release' requested here
   80 |       ConstRemovingRefPtrTraits<T>::Release(mRawPtr);
      |                                     ^
dom/media/MediaStreamTrack.h:130:10: note: in instantiation of member function 'RefPtr<mozilla::MediaTrack>::~RefPtr' requested here
  130 |   struct CloneResult {
      |          ^
dom/media/MediaStreamTrack.h:27:7: note: forward declaration of 'mozilla::MediaTrack'
   27 | class MediaTrack;
      |       ^

Differential Revision: https://phabricator.services.mozilla.com/D320830

UltraBlame original commit: 56c4731aa8f16396c2e2e67ba0cc4dec38f90af8