Bug 1958173 - Add missing constinit to gNumNormalOrHighPriorityQueuesHaveTaskScheduledMainThread definition. r=sefeng
When compiling as C++20, MOZ_CONSTINIT expands to constinit. Since gNumNormalOrHighPriorityQueuesHaveTaskScheduledMainThread's extern declaration in WebTaskScheduler.h was declared constinit, the definition in WebTaskSchedulerMainThread.cpp must also be constinit (MOZ_CONSTINIT).

dom/webscheduling/WebTaskSchedulerMainThread.cpp:15:10: error: 'constinit' specifier missing on initializing declaration of 'gNumNormalOrHighPriorityQueuesHaveTaskScheduledMainThread' [-Werror,-Wmissing-constinit]
   15 | uint32_t gNumNormalOrHighPriorityQueuesHaveTaskScheduledMainThread = 0;
      |          ^
dom/webscheduling/WebTaskScheduler.h:27:1: note: variable declared constinit here
   27 | MOZ_CONSTINIT extern uint32_t
      | ^

Differential Revision: https://phabricator.services.mozilla.com/D244285

UltraBlame original commit: fc93f8052ba8c9ab0a039ec75cb26ae0bfa06083