Bug 1998955 - Add missing includes to arm64 interceptor. r=win-reviewers,gstoll
When building with C++ for aarch64 windows, we get:

  /builds/worker/workspace/obj-build/dist/include/mozilla/interceptor/Arm64.h(200,45): error: expected ';' after expression
    200 |   Trampoline<typename TrampPoolT::MMPolicyT> veneer(
        |                                             ^
  /builds/worker/workspace/obj-build/dist/include/mozilla/interceptor/Arm64.h(200,3): error: use of undeclared identifier 'Trampoline'
    200 |   Trampoline<typename TrampPoolT::MMPolicyT> veneer(
        |   ^
  /builds/worker/workspace/obj-build/dist/include/mozilla/interceptor/Arm64.h(204,3): error: use of undeclared identifier 'veneer'
    204 |   veneer.WriteEncodedPointer(nullptr);
        |   ^
  /builds/worker/workspace/obj-build/dist/include/mozilla/interceptor/Arm64.h(205,3): error: use of undeclared identifier 'veneer'
    205 |   veneer.WriteEncodedPointer(aPrimaryTramp);
        |   ^
  /builds/worker/workspace/obj-build/dist/include/mozilla/interceptor/Arm64.h(207,3): error: use of undeclared identifier 'veneer'
    207 |   veneer.StartExecutableCode();
        |   ^

This seems like a missing include on a function that gets instantiated
or type-checked more eagerly with C++20.

Fix it by including the relevant file.

Differential Revision: https://phabricator.services.mozilla.com/D271777

UltraBlame original commit: cef6c9feed2da3c835c990e9f632b658fecc4af4