Bug 1903098 - Vendor libwebrtc from 6ab9085d19
Upstream commit: https://webrtc.googlesource.com/src/+/6ab9085d199e114f9382ae3893f4c5d80aba019f
    Fix iwyu error introduced recently.

    This fixes a build error introduced by:
    https://webrtc-review.googlesource.com/c/src/+/349001

    bot:
    https://ci.chromium.org/ui/p/chromium/builders/webrtc.fyi/WebRTC%20Chromium%20FYI%20ios-device

    Error:

    ../../third_party/webrtc/api/video_codecs/libaom_av1_encoder_factory.cc:494:27: error: expected ';' after expression
    494 |   rtc::SimpleStringBuilder sb(buf);
    |                           ^
    |                           ;
    ../../third_party/webrtc/api/video_codecs/libaom_av1_encoder_factory.cc:494:8: error: no member named 'SimpleStringBuilder' in namespace 'rtc'

    Bug: none
    Change-Id: I020040f367005ab56068cf4356e5effb380b7200
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/349320
    Auto-Submit: Tomas Gunnarsson <tommiwebrtc.org>
    Reviewed-by: Mirko Bonadei <mbonadeiwebrtc.org>
    Commit-Queue: Mirko Bonadei <mbonadeiwebrtc.org>
    Cr-Commit-Position: refs/heads/main{#42189}

UltraBlame original commit: 891f0eab825f4c88dd607332ad84bd59074f21a9