Bug 2030578 - ipc: Reorder PageUserCounters class definition in WindowGlobalParent.cpp. r=ipc-reviewers,mccr8
clang's C++23 unique_ptr's destructor requires a complete class definition, so
move PageUseCounters' class definition before WindowGlobalParent's constructor.

/Users/chris/.mozbuild/MacOSX26.2.sdk/usr/include/c++/v1/__memory/unique_ptr.h:76:19: error: invalid application of 'sizeof' to an incomplete type 'mozilla::dom::PageUseCounters'
   76 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
      |                   ^~~~~~~~~~~
dom/ipc/WindowGlobalParent.cpp:115:21: note: in instantiation of member function 'std::unique_ptr<mozilla::dom::PageUseCounters>::~unique_ptr' requested here
  115 | WindowGlobalParent::WindowGlobalParent(
      |                     ^
/Users/chris/Code/mozilla/firefox-git/obj-aarch64-apple-darwin25.4.0/dist/include/mozilla/dom/WindowGlobalParent.h:44:8: note: forward declaration of 'mozilla::dom::PageUseCounters'
   44 | struct PageUseCounters;
      |        ^

Differential Revision: https://phabricator.services.mozilla.com/D293010

UltraBlame original commit: bba8e3f63287ac6d7b390aa488b94177cbc7dea2